name: Clang Flow Checks
on: [push, pull_requests]

jobs:
    windows:
        runs-on: windows-latest
        strategy:
            matrix:
                clang-version: [11, 12, 13, latest]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Set up Clang
              uses: egor-tensin/setup-clang@v1
              with:
                  version: ${{matrix.clang-version}}
                  platform: x64
            - name: Run test
              run: |
                  clang -O3 -fno-vectorize -fno-unroll-loops -I./loops/vectorizable/ -DINCLUDE_TEST=\"test1.hpp\" test.cpp -emit-llvm -c -o test1.bc
                  llvm-extract -func=?run@testFunc@@QEAAXXZ test1.bc -o run-fn.bc
                  llvm-dis run-fn.bc -o run-fn.ll
